name: deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'test'
        type: choice
        options:
          - prod
          - stage
          - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ACCESS_KEY: ${{secrets.ACCESS_KEY}}
      ACCESS_SECRET: ${{secrets.ACCESS_SECRET}}
      ENV_BY_BRANCH: ""
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set environment variables
        id : set-env
        run: |
          if [ ${{ github.workflow_dispatch.inputs.environment }} = "prod" ]; then 
              echo "ENV_BY_BRANCH=${{ vars.PROD_ENV_BY_BRANCH }}" >> $ENV_BY_BRANCH
          elif [ ${{ github.workflow_dispatch.inputs.environment }} = "stage" ]; then 
              echo "ENV_BY_BRANCH=${{ vars.STAGE_ENV_BY_BRANCH }}" >> $ENV_BY_BRANCH
          elif [ ${{ github.workflow_dispatch.inputs.environment }} = "test" ]; then 
              echo "ENV_BY_BRANCH=${{ vars.DEV_ENV_BY_BRANCH }}" >> $ENV_BY_BRANCH
          fi

      - name: Building...
        run: |
          chmod +x ./code-to-build.sh
          ./code-to-build.sh ${{ env.ENV_BY_BRANCH }}  ${{ env.ACCESS_KEY }}  ${{ env.ACCESS_SECRET }}
