name: deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'test'
        type: choice
        options:
          - prod
          - stage
          - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ACCESS_KEY: ${{github.repository.secrets.ACCESS_KEY}}
      ACCESS_SECRET: ${{github.repository.secrets.ACCESS_SECRET}}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set environment variables
        id : set-env
        run: |
          case ${{ github.workflow_dispatch.inputs.environment }} in 
            ( prod )
              echo "ENV_BY_BRANCH=${{ github.repository.variables.PROD_ENV_BY_BRANCH }}" >> $GITHUB_ENV
              ;;
            ( stage )
              echo "ENV_BY_BRANCH=${{ github.repository.variables.STAGE_ENV_BY_BRANCH }}" >> $GITHUB_ENV
              ;;
            ( dev )
              echo "ENV_BY_BRANCH=${{ github.repository.variables.DEV_ENV_BY_BRANCH }}" >> $GITHUB_ENV
              ;;
          esac

      - name: Building...
        run: ./code-to-build.sh env.ENV_BY_BRANCH env.ACCESS_KEY, env.ACCESS_SECRET
